### ISSUE TITLE
config for Mediamill

### ISSUE THREAD

**Issue by yszd577** [Extreme-classification/deepxml#13]
Hello! 
When I run astec in Mediamill, it seems go wrong in ANN process. I got the following data error:
```
Caught ValueError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/home/pclab/Tools/anaconda/envs/deepxml/lib/python3.8/site-packages/torch/utils/data/_utils/worker.py", line 287, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/pclab/Tools/anaconda/envs/deepxml/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 49, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/pclab/Tools/anaconda/envs/deepxml/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 49, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/pclab/cyx/extreme_classification/programs/deepxml/deepxml/libs/dataset.py", line 298, in __getitem__
    y = self.get_shortlist(index)
  File "/home/pclab/cyx/extreme_classification/programs/deepxml/deepxml/libs/dataset.py", line 279, in get_shortlist
    return self.shortlist.get_shortlist(index, pos_labels)
  File "/home/pclab/cyx/extreme_classification/programs/deepxml/deepxml/libs/shortlist_handler.py", line 173, in get_shortlist
    return self._get_sl_one(index, pos_labels)
  File "/home/pclab/cyx/extreme_classification/programs/deepxml/deepxml/libs/shortlist_handler.py", line 133, in _get_sl_one
    shortlist, sim = self.query(index)
  File "/home/pclab/cyx/extreme_classification/programs/deepxml/deepxml/libs/shortlist_handler.py", line 325, in query
    _ind, _sim = self.shortlist_dynamic.query(1)
  File "/home/pclab/cyx/extreme_classification/programs/deepxml/deepxml/libs/sampling.py", line 44, in query
    return self._query()
  File "/home/pclab/cyx/extreme_classification/programs/deepxml/deepxml/libs/sampling.py", line 38, in _query
    return (self.index(size=self.num_samples), [1.0]*self.num_samples)
  File "_generator.pyx", line 769, in numpy.random._generator.Generator.choice
ValueError: Cannot take a larger sample than population when replace is False
  File "/home/pclab/cyx/extreme_classification/programs/deepxml/deepxml/libs/model_base.py", line 257, in _step
    for batch_data in pbar:
  File "/home/pclab/cyx/extreme_classification/programs/deepxml/deepxml/libs/model.py", line 305, in _fit
    tr_avg_loss = self._step(
  File "/home/pclab/cyx/extreme_classification/programs/deepxml/deepxml/libs/model.py", line 518, in fit
    self._fit(
  File "/home/pclab/cyx/extreme_classification/programs/deepxml/deepxml/main.py", line 70, in train
    train_time, model_size = model.fit(
  File "/home/pclab/cyx/extreme_classification/programs/deepxml/deepxml/main.py", line 420, in main
    output = train(model, params)
  File "/home/pclab/cyx/extreme_classification/programs/deepxml/deepxml/runner.py", line 156, in run_deepxml
    _train_time, _model_size = main(args)
  File "/home/pclab/cyx/extreme_classification/programs/deepxml/deepxml/runner.py", line 386, in run_one
    return run_deepxml(work_dir, version, seed, config)
  File "/home/pclab/cyx/extreme_classification/programs/deepxml/deepxml/runner.py", line 438, in <module>
    run_one(
 ```
I use the data in http://manikvarma.org/downloads/XC/XMLRepository.html and split accoriding to split file. Here's my config json:
```json
{
    "global": {
        **"dataset": "Mediamill",**
        "feature_type": "sparse",
        **"num_labels": 101,**
        "arch": "Astec",
        "A": 0.55,
        "B": 1.5,
        "use_reranker": true,
        **"surrogate_threshold": 32,**
        "surrogate_method": 1,
        **"embedding_dims": 100,**
        **"top_k": 20,**
	"beta": 0.3,
        "save_predictions": true,
        "trn_label_fname": "trn_X_Y.txt",
        "val_label_fname": "tst_X_Y.txt",
        "tst_label_fname": "tst_X_Y.txt",
        "trn_feat_fname": "trn_X_Xf.txt",
        "val_feat_fname": "tst_X_Xf.txt",
        "tst_feat_fname": "tst_X_Xf.txt"
    },
    "surrogate": {
        "num_epochs": 20,
        "dlr_factor": 0.5,
        "learning_rate": 0.01,
        "batch_size": 255,
        "dlr_step": 14,
        "normalize": true,
        **"init": null,**
        "optim": "Adam",
        "embeddings": "fasttextB_embeddings_300d.npy",
        "validate": true,
        "save_intermediate": true
    },
    "extreme": {
        "num_epochs": 20,
        "dlr_factor": 0.5,
        "learning_rate": 0.007,
        "batch_size": 255,
        "dlr_step": 14,
        "ns_method": "ensemble",
        "num_centroids": 1,
        "efC": 300,
        **"efS": 20,**
        "M": 100,
        "num_nbrs": 500,
        "ann_threads": 18,
        "beta": 0.5,
        "surrogate_mapping": true,
        "num_clf_partitions": 1,
        "optim": "Adam",
        "freeze_intermediate": true,
        "validate": true,
        "model_method": "shortlist",
        "normalize": true,
        "shortlist_method": "hybrid",
        "init": "intermediate",
        "use_shortlist": true,
        "use_intermediate_for_shorty": true
    },
    "reranker": {
        "num_epochs": 15,
        "dlr_factor": 0.5,
        "learning_rate": 0.005,
        "batch_size": 255,
        "dlr_step": 10,
        "beta": 0.6,
        "num_clf_partitions": 1,
        "optim": "Adam",
        "validate": true,
        "model_method": "reranker",
        "shortlist_method": "static",
        "surrogate_mapping": null,
        "normalize": true,
        "use_shortlist": true,
        "init": null,
        "save_intermediate": false,
        "keep_invalid": true,
        "freeze_intermediate": false,
        "update_shortlist": false,
        "use_pretrained_shortlist": true,
        "embeddings": "fasttextB_embeddings_300d.npy"
    }
}
```
my command is `./run_main.sh 0 DeepXML Mediamill 1 108`

**Comment by kunaldahiya** [comment]
Hi,

Thanks for checking out, DeepXML. The dataset is too small for DeepXML to demonstrate any benefit, you can simply use DeepXML-OVA which will jointly learn the embeddings alongside the classifiers.  

For completeness: DeepXML's Module-IV adds some random negatives for each document - the value is set to 150 ([by default](https://github.com/Extreme-classification/deepxml/blob/254f93779ba1e43931eada128e1e2b3bb02f74f3/deepxml/libs/dataset.py#L241)) which is more than the number of labels in this dataset. Please note that the labels are sampled without replacement [by default](https://github.com/Extreme-classification/deepxml/blob/254f93779ba1e43931eada128e1e2b3bb02f74f3/deepxml/libs/sampling.py#L82) - hence the error.

--
KD
